# Generated by Django 4.2 on 2026-02-04 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import packagehandling.models.user


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(blank=True, max_length=150, null=True, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", packagehandling.models.user.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("identification_number", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("main_street", models.CharField(blank=True, max_length=255, null=True)),
                ("secondary_street", models.CharField(blank=True, max_length=255, null=True)),
                ("building_number", models.CharField(blank=True, max_length=255, null=True)),
                ("mobile_phone_number", models.CharField(blank=True, max_length=255, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Consolidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_payment", "Awaiting Payment"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("in_transit", "In Transit"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("comment", models.TextField(blank=True, null=True)),
                ("extra_attributes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidates",
                        to="packagehandling.client",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("barcode", models.CharField(max_length=255, unique=True)),
                ("courier", models.CharField(max_length=255)),
                ("other_courier", models.CharField(blank=True, max_length=255, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("width", models.FloatField(blank=True, null=True)),
                ("height", models.FloatField(blank=True, null=True)),
                ("dimension_unit", models.CharField(blank=True, max_length=10, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("weight_unit", models.CharField(blank=True, max_length=10, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("purchase_link", models.URLField(blank=True, null=True)),
                ("real_price", models.FloatField(blank=True, null=True)),
                ("service_price", models.FloatField(blank=True, null=True)),
                ("arrival_date", models.DateField(blank=True, null=True)),
                ("comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packages",
                        to="packagehandling.client",
                    ),
                ),
                (
                    "consolidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="packages",
                        to="packagehandling.consolidate",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["barcode"], name="packagehand_barcode_745d0a_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["client", "-created_at"], name="packagehand_client__2de70d_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["consolidate"], name="packagehand_consoli_647357_idx"),
        ),
        migrations.AddIndex(
            model_name="package",
            index=models.Index(fields=["arrival_date"], name="packagehand_arrival_8db9ff_idx"),
        ),
        migrations.AddIndex(
            model_name="consolidate",
            index=models.Index(fields=["client", "-created_at"], name="packagehand_client__14c92e_idx"),
        ),
        migrations.AddIndex(
            model_name="consolidate",
            index=models.Index(fields=["status"], name="packagehand_status_b07b97_idx"),
        ),
        migrations.AddIndex(
            model_name="consolidate",
            index=models.Index(fields=["delivery_date"], name="packagehand_deliver_94601c_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="packagehand_email_a2f156_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["identification_number"], name="packagehand_identif_47aa82_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["created_at"], name="packagehand_created_b81e35_idx"),
        ),
    ]
