# Generated by Django 4.2.24 on 2025-09-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packagehandling', '0002_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='client_id',
        ),
        migrations.AddField(
            model_name='package',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packagehandling.client'),
        ),
    ]
