# Generated by Django 4.2 on 2025-10-19 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagehandling", "0002_alter_client_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consolidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("status", models.CharField(max_length=255)),
                ("delivery_date", models.DateField()),
                ("comment", models.TextField(blank=True, null=True)),
                ("extra_attributes", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consolidates",
                        to="packagehandling.client",
                    ),
                ),
                ("packages", models.ManyToManyField(related_name="consolidates", to="packagehandling.package")),
            ],
        ),
    ]
