# Generated by Django 4.2.24 on 2025-09-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packagehandling', '0003_remove_package_client_id_package_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='packagehandling.client'),
        ),
    ]
