# Generated by Django 4.2 on 2025-10-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagehandling", "0003_consolidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consolidate",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
