# Generated by Django 4.2 on 2025-10-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagehandling", "0004_alter_consolidate_delivery_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
