# Generated by Django 4.2.24 on 2025-09-23 19:05

from django.db import migrations

def create_client_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Client')

def remove_client_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Client').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('packagehandling', '0004_alter_package_client'),
    ]

    operations = [
        migrations.RunPython(create_client_group, remove_client_group),
    ]
