# Generated by Django 4.2 on 2025-10-28 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagehandling", "0005_package_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="barcode",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
