# Generated by Django 4.2 on 2025-10-29 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagehandling", "0006_alter_package_barcode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consolidate",
            name="packages",
        ),
        migrations.AddField(
            model_name="package",
            name="consolidate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="packages",
                to="packagehandling.consolidate",
            ),
        ),
    ]
