# Generated by Django 4.2 on 2025-10-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packagehandling", "0007_remove_consolidate_packages_package_consolidate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consolidate",
            name="status",
            field=models.CharField(
                choices=[
                    ("awaiting_payment", "Awaiting Payment"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
