services:
  db:
    image: postgres:16
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: 'mydatabase'
      POSTGRES_USER: 'myuser'
      POSTGRES_PASSWORD: 'mypassword'
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${DB_PORT:-5432}:5432"

  web:
    build: .
    container_name: nbxdjango-web
    command: python nbxdjango/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/mydatabase
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=password
    depends_on:
      - db

volumes:
  postgres_data:
