name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install flake8 black isort
      - name: Run flake8
        run: flake8 .
      - name: Check code formatting
        run: black --check .
      - name: Check import sorting
        run: isort --check-only .